version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: "host"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
  